### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by cmcaine** [zsh-users/zsh-docker#13]
Hi, what's the intended use of this project?

**Comment by guidovansteen** [comment]
Using this project you can run any version of zsh in Docker container. Useful if you want to test a specific version. Or if you want to use zsh, but you do not want to install it.

**Comment by cmcaine** [comment]
So let's say you want to use zsh but not install it. Do you volume mount root of the host system and then fiddle with path or something? Or are you intended to work in the docker container and not touch the host?

Could you share an example docker invocation for these use cases?

I'm sorry if my questions are daft.
