### ISSUE TITLE
MONITOR option (job control) can't be enabled

### ISSUE THREAD

**Issue by ericfreese** [zsh-users/zsh-docker#14]
Job control appears to be disabled inside the container. 

```
% docker run -it --rm zshusers/zsh-5.6.2 zsh
% bg
bg: no job control in this shell.
% setopt
interactive
shinstdin
zle
% setopt monitor
setopt: can't change option: monitor
```

Relevant zsh code seems to be here: 

- https://github.com/zsh-users/zsh/blob/c749a06bc9f15b5153d55b7f5e6f9a3a252e39f6/Src/options.c#L608
- https://github.com/zsh-users/zsh/blob/c749a06bc9f15b5153d55b7f5e6f9a3a252e39f6/Src/options.c#L802-L814

It seems that either `SHTTY` is `-1` or `JOB_CONTROL` is not defined at compile time.

Anyone know exactly what's going on here? Can we change the docker setup to support job control inside the containers?

**Comment by nicoulaj** [comment]
Should be fixed by #15
