### ISSUE TITLE
zsh-master: add git hash

### ISSUE THREAD

**Issue by nicoulaj** [zsh-users/zsh-docker#2]
The `zsh-master` image does not have a more precise info than its build, we somehow need the git hash to make it usable (in repo description (%1) ? as a tag name ?)

**Comment by danielshahaf** [comment]
> The `zsh-master` image does not have a more precise info than its build, we somehow need the git hash to make it usable (in repo description (%1) ? as a tag name ?)

The git hash is available as $ZSH_PATCHLEVEL.

**Comment by nicoulaj** [comment]
@danielshahaf: ok, so I guess it is no really an issue for zsh-syntax-highlighting, we can just add something like `zsh -fc 'echo $ZSH_PATCHLEVEL'` at the start of `make test`.

**Comment by nicoulaj** [comment]
Not needed, closing
