### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by nicoulaj** [zsh-users/zsh-docker#5]
The image size is pretty big (310MB). It can be reduced by uninstalling the compile-time only dependencies after build.

**Comment by nicoulaj** [comment]
Status:
 * Images are now squashed (size is only reduced from 310MB to 290MB on current master) => merged on master
 * the `alpine-linux` branch moves from Debian to Alpine Linux as the base image. The image size is reduced from 310MB to 15MB with squashing => not merged on master, as zsh test suite does not seem to work well with busybox instead of GNU coreutils (see [this build](https://travis-ci.org/zsh-users/zsh-docker/builds/260284977))

**Comment by nicoulaj** [comment]
Status:
 * On `master` the image size has been reduced from 310MB to 78MB by removing build dependencies and squashing. 
 * the `alpine-linux` branch moves from Debian to Alpine Linux as the base image. The image size is reduced to 15MB => not merged on master, as zsh test suite does not seem to work well with busybox/musl instead of GNU libc/coreutils (see [this build](https://travis-ci.org/zsh-users/zsh-docker/builds/260284977))

**Comment by danielshahaf** [comment]
> zsh test suite does not seem to work well with busybox/musl instead of GNU libc/coreutils (see this build)

D03 fails because the `diff` tool on alpine is not POSIX compliant.  See http://pubs.opengroup.org/onlinepubs/9699919799/utilities/diff.html#tag_20_34_10_03 (output form when invoked with two file operands).

**Comment by nicoulaj** [comment]
Yes, this one could be fixed easily by installing `diffutils`.

The remaining failures are:
```
Test ./V09datetime.ztst failed: bad status 1, expected 0 from:
  [[ $(strftime '%@' 0 2> /dev/null) == (%|)@ || $? != 0 ]]
```
=> looks like musl's strftime() does not implement some extensions, and the test handles it incorrectly

```
./A01grammar.ztst: starting.
Test ./A01grammar.ztst failed: bad status 127, expected 0 from:
  (exec -a /bin/SPLATTER /bin/sh -c 'echo $0')
Error output:
SPLATTER: applet not found
Was testing: `exec' with -a option
./A01grammar.ztst: test failed.
```
=> not sure what happens here

**Comment by danielshahaf** [comment]
> ```
> ./A01grammar.ztst: starting.
> Test ./A01grammar.ztst failed: bad status 127, expected 0 from:
>   (exec -a /bin/SPLATTER /bin/sh -c 'echo $0')
> Error output:
> SPLATTER: applet not found
> Was testing: `exec' with -a option
> ./A01grammar.ztst: test failed.
> ```
> => not sure what happens here

Does /etc/zshenv define a function called 'exec'?

**Comment by nicoulaj** [comment]
No, `/etc/zshenv` does not exist.

**Comment by danielshahaf** [comment]
> No, `/etc/zshenv` does not exist.

Thanks for checking.

How about trying to reproduce the problem minimally:

python -c 'import os; os.execv("/bin/sh", ["/bin/SPLATTER", "-c", "echo $0"])'

Does that print "/bin/SPLATTER" or an error message?

**Comment by nicoulaj** [comment]
```
Step 20/27 : RUN python -c 'import os; os.execv("/bin/sh", ["/bin/SPLATTER", "-c", "echo $0"])'
 ---> Running in 256cd4bca283
SPLATTER: applet not found
The command '/bin/sh -c python -c 'import os; os.execv("/bin/sh", ["/bin/SPLATTER", "-c", "echo $0"])'' returned a non-zero code: 127
```
From a quick look at busybox docs, it seems it refers to core utilities as "applets" (and may be considers `/bin` as a special path). The exit code `127` might be incorrectly handled by the test.

**Comment by nicoulaj** [comment]
Image size is down to 25MB thanks to multi-stage build + minideb.
